"""empty message

Revision ID: 2c25be162ebb
Revises: 602c40a01ac8
Create Date: 2018-08-30 09:54:15.270131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c25be162ebb'
down_revision = '602c40a01ac8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('collection_ibfk_2', 'collection', type_='foreignkey')
    op.drop_constraint('collection_ibfk_1', 'collection', type_='foreignkey')
    op.create_foreign_key(None, 'collection', 'user', ['user_id'], ['id'], onupdate='SET NULL', ondelete='SET NULL')
    op.create_foreign_key(None, 'collection', 'movie', ['movie_id'], ['id'], onupdate='SET NULL', ondelete='SET NULL')
    op.drop_constraint('comment_ibfk_2', 'comment', type_='foreignkey')
    op.drop_constraint('comment_ibfk_1', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['id'], onupdate='SET NULL', ondelete='SET NULL')
    op.create_foreign_key(None, 'comment', 'movie', ['movie_id'], ['id'], onupdate='SET NULL', ondelete='SET NULL')
    op.drop_constraint('loginlog_ibfk_1', 'loginlog', type_='foreignkey')
    op.create_foreign_key(None, 'loginlog', 'user', ['user_id'], ['id'], onupdate='SET NULL', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'loginlog', type_='foreignkey')
    op.create_foreign_key('loginlog_ibfk_1', 'loginlog', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_ibfk_1', 'comment', 'movie', ['movie_id'], ['id'])
    op.create_foreign_key('comment_ibfk_2', 'comment', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'collection', type_='foreignkey')
    op.drop_constraint(None, 'collection', type_='foreignkey')
    op.create_foreign_key('collection_ibfk_1', 'collection', 'movie', ['movie_id'], ['id'])
    op.create_foreign_key('collection_ibfk_2', 'collection', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
