"""empty message

Revision ID: 44733d444eff
Revises: 14f5e0614691
Create Date: 2018-09-09 10:33:02.498873

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '44733d444eff'
down_revision = '14f5e0614691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin', 'pwd',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin', 'pwd',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###
