"""empty message

Revision ID: 5316617d7141
Revises: 571fc65443df
Create Date: 2018-09-06 20:01:22.232094

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5316617d7141'
down_revision = '571fc65443df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'name',
               existing_type=mysql.VARCHAR(charset='utf8', length=30),
               nullable=False)
    op.drop_column('role', 'auths')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('auths', mysql.VARCHAR(length=60), nullable=False))
    op.alter_column('role', 'name',
               existing_type=mysql.VARCHAR(charset='utf8', length=30),
               nullable=True)
    # ### end Alembic commands ###
