"""empty message

Revision ID: 56b4b4540853
Revises: d0dabf2563ee
Create Date: 2018-08-31 16:18:59.995635

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '56b4b4540853'
down_revision = 'd0dabf2563ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('adminlog_ibfk_1', 'adminlog', type_='foreignkey')
    op.create_foreign_key(None, 'adminlog', 'admin', ['admin_id'], ['id'], onupdate='SET NULL', ondelete='SET NULL')
    op.drop_constraint('oplog_ibfk_1', 'oplog', type_='foreignkey')
    op.create_foreign_key(None, 'oplog', 'admin', ['admin_id'], ['id'], onupdate='SET NULL', ondelete='SET NULL')
    op.add_column('user', sa.Column('nickname', sa.String(length=30), nullable=False))
    op.alter_column('user', 'info',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('user', 'userName',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.drop_index('userName', table_name='user')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', mysql.VARCHAR(length=30), nullable=False))
    op.create_index('userName', 'user', ['userName'], unique=True)
    op.alter_column('user', 'userName',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('user', 'info',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.drop_column('user', 'nickname')
    op.drop_constraint(None, 'oplog', type_='foreignkey')
    op.create_foreign_key('oplog_ibfk_1', 'oplog', 'admin', ['admin_id'], ['id'])
    op.drop_constraint(None, 'adminlog', type_='foreignkey')
    op.create_foreign_key('adminlog_ibfk_1', 'adminlog', 'admin', ['admin_id'], ['id'])
    # ### end Alembic commands ###
