"""empty message

Revision ID: 571fc65443df
Revises: 2f0ce0ffb3fe
Create Date: 2018-09-06 19:35:23.006358

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '571fc65443df'
down_revision = '2f0ce0ffb3fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'admin', ['name'])
    op.create_unique_constraint(None, 'auth', ['name'])
    op.create_unique_constraint(None, 'role', ['name'])
    op.alter_column('tag', 'tagName',
               existing_type=mysql.VARCHAR(charset='utf8', length=50),
               nullable=False)
    op.create_unique_constraint(None, 'tag', ['tagName'])
    op.create_unique_constraint(None, 'user', ['nickname'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'tag', type_='unique')
    op.alter_column('tag', 'tagName',
               existing_type=mysql.VARCHAR(charset='utf8', length=50),
               nullable=True)
    op.drop_constraint(None, 'role', type_='unique')
    op.drop_constraint(None, 'auth', type_='unique')
    op.drop_constraint(None, 'admin', type_='unique')
    # ### end Alembic commands ###
