"""empty message

Revision ID: 602c40a01ac8
Revises: 99096228d9ad
Create Date: 2018-08-30 09:51:53.175181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '602c40a01ac8'
down_revision = '99096228d9ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['userName'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
