"""empty message

Revision ID: 774d0cd9998c
Revises: 44733d444eff
Create Date: 2018-09-09 11:02:45.154848

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '774d0cd9998c'
down_revision = '44733d444eff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movie', 'length',
               existing_type=mysql.VARCHAR(charset='utf8', length=50),
               nullable=False)
    op.alter_column('movie', 'url',
               existing_type=mysql.VARCHAR(charset='utf8', length=100),
               type_=sa.String(length=600),
               nullable=False)
    op.add_column('user', sa.Column('registTime', sa.DateTime(), nullable=True))
    op.drop_column('user', 'loginTime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('loginTime', mysql.DATETIME(), nullable=True))
    op.drop_column('user', 'registTime')
    op.alter_column('movie', 'url',
               existing_type=sa.String(length=600),
               type_=mysql.VARCHAR(charset='utf8', length=100),
               nullable=True)
    op.alter_column('movie', 'length',
               existing_type=mysql.VARCHAR(charset='utf8', length=50),
               nullable=True)
    # ### end Alembic commands ###
