"""empty message

Revision ID: 99096228d9ad
Revises: 79a56dd71e62
Create Date: 2018-08-30 09:17:30.448958

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '99096228d9ad'
down_revision = '79a56dd71e62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_tag',
    sa.Column('tag_id', sa.INTEGER(), nullable=True),
    sa.Column('movie_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    op.drop_column('movie', 'tag_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('tag_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_table('movie_tag')
    # ### end Alembic commands ###
