"""empty message

Revision ID: 9eff55524c0b
Revises: 56b4b4540853
Create Date: 2018-08-31 17:12:27.969442

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9eff55524c0b'
down_revision = '56b4b4540853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'face',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('user', 'loginTime',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('user', 'uuid',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'uuid',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    op.alter_column('user', 'loginTime',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('user', 'face',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    # ### end Alembic commands ###
