"""empty message

Revision ID: b26c0ac1a2ba
Revises: f59701ecf331
Create Date: 2018-09-08 18:10:19.512704

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b26c0ac1a2ba'
down_revision = 'f59701ecf331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movie', 'length',
               existing_type=mysql.TIME(),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movie', 'length',
               existing_type=sa.String(length=50),
               type_=mysql.TIME(),
               existing_nullable=False)
    # ### end Alembic commands ###
