"""empty message

Revision ID: c447363f7efe
Revises: d6564733aafc
Create Date: 2018-08-29 17:45:52.086900

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c447363f7efe'
down_revision = 'd6564733aafc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'content',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'content',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
