"""empty message

Revision ID: d0dabf2563ee
Revises: 2c25be162ebb
Create Date: 2018-08-30 10:10:29.271914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0dabf2563ee'
down_revision = '2c25be162ebb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('movie_tag_ibfk_2', 'movie_tag', type_='foreignkey')
    op.drop_constraint('movie_tag_ibfk_1', 'movie_tag', type_='foreignkey')
    op.create_foreign_key(None, 'movie_tag', 'tag', ['tag_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'movie_tag', 'movie', ['movie_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movie_tag', type_='foreignkey')
    op.drop_constraint(None, 'movie_tag', type_='foreignkey')
    op.create_foreign_key('movie_tag_ibfk_1', 'movie_tag', 'movie', ['movie_id'], ['id'])
    op.create_foreign_key('movie_tag_ibfk_2', 'movie_tag', 'tag', ['tag_id'], ['id'])
    # ### end Alembic commands ###
