"""empty message

Revision ID: d836e2a13371
Revises: 5316617d7141
Create Date: 2018-09-06 20:06:45.331521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd836e2a13371'
down_revision = '5316617d7141'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth', sa.Column('role', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'auth', 'role', ['role'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'auth', type_='foreignkey')
    op.drop_column('auth', 'role')
    # ### end Alembic commands ###
