"""empty message

Revision ID: e5218b9eb779
Revises: 7120a04ba457
Create Date: 2018-09-08 22:24:30.982195

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e5218b9eb779'
down_revision = '7120a04ba457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('auth_ibfk_1', 'auth', type_='foreignkey')
    op.create_foreign_key(None, 'auth', 'role', ['role'], ['id'], ondelete='SET NULL')
    op.alter_column('movie', 'area',
               existing_type=mysql.VARCHAR(charset='utf8', length=50),
               nullable=False)
    op.alter_column('movie', 'info',
               existing_type=mysql.VARCHAR(charset='utf8', length=500),
               nullable=False)
    op.alter_column('movie', 'length',
               existing_type=mysql.VARCHAR(charset='utf8', length=30),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('movie', 'logo',
               existing_type=mysql.VARCHAR(charset='utf8', length=50),
               nullable=False)
    op.alter_column('movie', 'title',
               existing_type=mysql.VARCHAR(charset='utf8', length=30),
               nullable=False)
    op.alter_column('movie', 'url',
               existing_type=mysql.VARCHAR(charset='utf8', length=500),
               type_=sa.String(length=600),
               nullable=False)
    op.alter_column('preview', 'logo',
               existing_type=mysql.VARCHAR(charset='utf8', length=50),
               nullable=False)
    op.alter_column('preview', 'title',
               existing_type=mysql.VARCHAR(charset='utf8', length=50),
               nullable=False)
    op.drop_constraint('role_ibfk_1', 'role', type_='foreignkey')
    op.create_foreign_key(None, 'role', 'admin', ['admin'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role', type_='foreignkey')
    op.create_foreign_key('role_ibfk_1', 'role', 'admin', ['admin'], ['id'])
    op.alter_column('preview', 'title',
               existing_type=mysql.VARCHAR(charset='utf8', length=50),
               nullable=True)
    op.alter_column('preview', 'logo',
               existing_type=mysql.VARCHAR(charset='utf8', length=50),
               nullable=True)
    op.alter_column('movie', 'url',
               existing_type=sa.String(length=600),
               type_=mysql.VARCHAR(charset='utf8', length=500),
               nullable=True)
    op.alter_column('movie', 'title',
               existing_type=mysql.VARCHAR(charset='utf8', length=30),
               nullable=True)
    op.alter_column('movie', 'logo',
               existing_type=mysql.VARCHAR(charset='utf8', length=50),
               nullable=True)
    op.alter_column('movie', 'length',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(charset='utf8', length=30),
               nullable=True)
    op.alter_column('movie', 'info',
               existing_type=mysql.VARCHAR(charset='utf8', length=500),
               nullable=True)
    op.alter_column('movie', 'area',
               existing_type=mysql.VARCHAR(charset='utf8', length=50),
               nullable=True)
    op.drop_constraint(None, 'auth', type_='foreignkey')
    op.create_foreign_key('auth_ibfk_1', 'auth', 'role', ['role'], ['id'])
    # ### end Alembic commands ###
