"""empty message

Revision ID: f59701ecf331
Revises: 9a1450638df8
Create Date: 2018-09-07 16:38:40.651146

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f59701ecf331'
down_revision = '9a1450638df8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movie', 'length',
               existing_type=mysql.DATETIME(),
               type_=sa.Time(),
               existing_nullable=False)
    op.alter_column('movie', 'release_time',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movie', 'release_time',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=False)
    op.alter_column('movie', 'length',
               existing_type=sa.Time(),
               type_=mysql.DATETIME(),
               existing_nullable=False)
    # ### end Alembic commands ###
